### Q1: Building Class Register

**Task 1**

Build one table from s1, s2 and s3.

**Task 2**

For that table, print the number of students and the number of subjects as two separate numbers.

**Task 3**

Print the total count of marks entries stored in the table.

**Task 4**

Store the same table as decimals instead of whole numbers.

**Task 5**

Convert old into a form where arithmetic works, then print the total marks of both students.

Expected output:

`[268 246]`

**Task 6**

Attach old below the main table so that all five students sit in one table.

Expected output:

`[[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]
 [ 62  71  55  80]
 [ 49  58  66  73]]`

In [ ]:
s1 = np.array([35, 69, 75])
s2 = np.array([44, 32, 90])
s3 = np.array([50, 60, 70]) 
print(table := np.vstack((s1,s2,s3)))
print("Number of Students :", table.shape[0])
print("Number of Subjects :", table.shape[1])
print("Total Count of Marks Entries :", table.size)

[[35 69 75]
 [44 32 90]
 [50 60 70]]
Number of Students : 3
Number of Subjects : 3
Total Count of Marks Entries : 9


### Q2 Templates and Sequences

### Tasks

- Create a blank mark sheet for 6 students and 4 subjects, every entry starting at 0.
- Create a table of the same size where every student is temporarily given 35.
- A batch has roll numbers running from 101 to 130. Generate only the alternate roll numbers, and print how many were generated.
- Split a 3-hour practical into 7 equally spaced time markers, including both the start and the end.
- Create a 5 × 5 table that has 10 on the diagonal and 0 everywhere else.
- Create a 4 × 4 table that has 100 on the diagonal and 35 everywhere else.

In [ ]:
students = np.zeros((6,4))
print("Task 1:", students)
marks = np.full((6,4), 35)
print("Task 2:", marks)
roll_numbers = np.arange(101, 131, 2)
print("Task 3:", roll_numbers)
equal_time_markers = np.linspace(0, 3, 7)
print("Task 4:", equal_time_markers)
table1 = np.eye(5) * 10
print("Task 5:", table1)   
table2 = np.full((4,4), 35)
print("Task 6:", table2)

Task 1: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Task 2: [[35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]]
Task 3: [101 103 105 107 109 111 113 115 117 119 121 123 125 127 129]
Task 4: [0.  0.5 1.  1.5 2.  2.5 3. ]
Task 5: [[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]
Task 6: [[35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]]


### Q3 The attendance row

1. Print the first and the last student's attendance without writing the class strength anywhere in your code.

2. Print the attendance of every alternate student, starting from the second one.

3. Print the last four values.

4. Reverse the row, then print every third value of the reversed row.

5. Change the attendance of the two middle students to 30 each.

6. Compare the first half of the row with the second half position by position, and print the difference.

7. Print the top three values of the row after reversing it.

In [ ]:
print(attendance := np.array([22, 18, 25, 12, 20, 24, 9, 21, 17, 23]))
print(attendance[[0, -1]])
print(attendance[1::2])
print(attendance[-4:])
reverse_attendance = attendance[::-1]
print(reverse_attendance[::3])
reverse_attendance[3:5] = 30
print(reverse_attendance)
print(reverse_attendance[:5] - reverse_attendance[5:])
print(np.sort(reverse_attendance)[-3:][::-1])

[22 18 25 12 20 24  9 21 17 23]
[22 23]
[18 12 24 21 23]
[ 9 21 17 23]
[23  9 12 22]
[23 17 21 30 30 20 12 25 18 22]
[ 3  5 -4 12  8]
[30 30 25]


### Q4 Reading the mark sheet

1. Print the Physics and Chemistry marks of the middle three students only.

2. Print the last subject's marks for the whole class.

3. Produce a table containing only the first and the last subject of every student.

4. Print the mark sheet with the students in reverse order.

5. Increase only the Chemistry marks of the whole class by 5, leaving the rest unchanged.

6. Print the mark that sits in the last row and the second-last column.

7. Produce a table of the last two students and their first two subjects.