# Numpy Questions

### Q1

Create an array of the first 12 odd numbers using a single np.arange call

In [2]:
# Q1 

import numpy as np
arr = np.arange(1, 24, 2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23]


### Q2 

Using np.linspace, create 9 equally spaced values from 5 to 45. Before running, predict the gap between consecutive values - then verify

In [3]:
# Q2 

arr = np.linspace(5, 45, 9)
print(arr)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45.]


### Q3

Create np.arange(1, 10) and np.linspace(1, 9, 9). Print both and compare their dtype. Why are
they different?

In [4]:
# Q3 
arr1 = np.arange(1, 10)
arr2 = np.linspace(1, 9, 9)
print("arr1:", arr1, "dtype:", arr1.dtype)
print("arr2:", arr2, "dtype:", arr2.dtype)

arr1: [1 2 3 4 5 6 7 8 9] dtype: int64
arr2: [1. 2. 3. 4. 5. 6. 7. 8. 9.] dtype: float64


### Q4

Create a 6x6 identity matrix with integer dtype - the output must show no decimal points.

In [5]:
# Q4 

arr = np.eye(6, dtype=int)
print(arr)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


### Q5

Create a 3x4 matrix where every element is 5, and report its shape, size, and ndim.

In [9]:
# Q5 

arr = np.full((3, 4), 5)
print("Array:\n", arr)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dimensions:", arr.ndim)

Array:
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
Shape: (3, 4)
Size: 12
Dimensions: 2


### Q6

Given a = np.array([2, 4, 6]) and b = np.array([2.0, 4.0, 6.0]) - check both dtypes, then convert b
to int with astype and verify the dtypes now match.

In [10]:
# Q6  

a = np.array([2, 4, 6])
b = np.array([2.0, 4.0, 6.0])
print("Before:")
print("a dtype:", a.dtype)
print("b dtype:", b.dtype)

b = b.astype(int)
print("\nAfter:")
print("a dtype:", a.dtype)
print("b dtype:", b.dtype)


Before:
a dtype: int64
b dtype: float64

After:
a dtype: int64
b dtype: int64


### Q7

Predict the exact output of np.array([10.9, 25.5, 39.99]).astype(int) before running it. What rule
does the result prove?

In [11]:
# Q7 

arr = np.array([10.9, 25.5, 39.99]).astype(int)
print(arr)

[10 25 39]


### Q8

Given arr = np.arange(10, 101, 10) - extract: 

(a) the 4th element

(b) the last element using negative indexing 

(c) the 2nd-last element.

In [12]:
# Q8 

arr = np.arange(10, 101, 10)

# (a) 4th element
print(arr[3])

# (b) Last element using negative indexing
print(arr[-1])

# (c) 2nd-last element
print(arr[-2])

40
100
90


### Q9

From the same arr, slice out exactly [30 40 50 60], and separately produce the full array in
reverse.

In [13]:
# Q9

arr = np.arange(10, 101, 10)
print(arr[2:6])
print(arr[::-1])

[30 40 50 60]
[100  90  80  70  60  50  40  30  20  10]


### Q10

Given arr = np.arange(1, 21) - extract every 3rd element starting from index 1 (result: 2, 5, 8, ...).

In [14]:
# Q10 

arr = np.arange(1, 21)
result = arr[1::3]
print(result)

[ 2  5  8 11 14 17 20]


### Q11

Using one slice only, extract everything from arr (1-20) EXCEPT the first two and the last two
elements.

In [16]:
# Q11

arr = np.arange(1, 21)
print(arr[2:-2])

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


### Q12

Using the matrix below, extract: (a) the 3rd row, (b) the last column, (c) the centre 3x3 block.

m = np.array([[ 1, 2, 3, 4, 5],
 
              [ 6, 7, 8, 9, 10],
 
              [11, 12, 13, 14, 15],
 
              [16, 17, 18, 19, 20],
 
              [21, 22, 23, 24, 25]])

In [17]:
# Q12

m = np.array([[ 1,  2,  3,  4,  5],
              [ 6,  7,  8,  9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25]])

# (a) 3rd row
print(m[2])

# (b) Last column
print(m[:, -1])

# (c) Centre 3x3 block
print(m[1:4, 1:4])

[11 12 13 14 15]
[ 5 10 15 20 25]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


### Q13

From the same matrix, extract the four corner elements as a 2x2 array - using step slicing only.

In [18]:
# Q13

import numpy as np

m = np.array([[ 1,  2,  3,  4,  5],
              [ 6,  7,  8,  9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25]])

print(m[::4, ::4])

[[ 1  5]
 [21 25]]


### Q14

From the same matrix, extract every alternate row AND every alternate column at the same time (the result is 3x3).

In [19]:
# Q13

m = np.array([[ 1,  2,  3,  4,  5],
              [ 6,  7,  8,  9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25]])

print(m[::2, ::2])

[[ 1  3  5]
 [11 13 15]
 [21 23 25]]


### Q15

Given the marks array below - (a) extract all marks greater than 60; (b) extract marks between 50 and 80 using two conditions with & (remember the parentheses!).

marks = np.array([56, 91, 44, 77, 62, 85, 39, 70])

In [20]:
# Q15

marks = np.array([56, 91, 44, 77, 62, 85, 39, 70])

# (a) Marks greater than 60
print(marks[marks > 60])

# (b) Marks between 50 and 80
print(marks[(marks >= 50) & (marks <= 80)])

[91 77 62 85 70]
[56 77 62 70]
