# NumPy

## What is NumPy

> **Flow**: Lists VS Arrays (speed, memory) -> **ndarray** -> the idea of vectorization -> Pandas/Sklearn are built on top of NumPy -> import as **np**

In [2]:
#np.array() - 1D and 2D

import numpy as np
x = np.array([2,3,4,5])
x1 = np.array([[2,3],[4,5],[8,9]])
print(x)
print(x.dtype)
print(type(x))
print(x1)

[2 3 4 5]
int64
<class 'numpy.ndarray'>
[[2 3]
 [4 5]
 [8 9]]


In [19]:
# np.zeros()

print(np.zeros(20))
print(np.zeros(10,dtype='int32'))
print(np.zeros((3,4), dtype='int16'))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [24]:
# np.ones()

print(np.ones(10))
print(np.ones((2,3,4)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [25]:
#  np.full()

print(np.full((4,3), 15))

[[15 15 15]
 [15 15 15]
 [15 15 15]
 [15 15 15]]


In [30]:
# np.arange(start, stop, step)

print(np.arange(10,5,-2))
print(np.arange(10))
print(np.arange(1,11).reshape(2,5))

[10  8  6]
[0 1 2 3 4 5 6 7 8 9]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [32]:
# np.linspace(start, stop, num)

print(np.linspace(1,10,5))
print(np.linspace(0,1,5))

[ 1.    3.25  5.5   7.75 10.  ]
[0.   0.25 0.5  0.75 1.  ]


In [5]:
# np.eye(n) - returns a 2-D array with ones on the diagonal and zeros elsewhere

print(np.eye(4))
# print(np.eye(3,4,k=2))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Array Attributes

In [36]:
# .shape() - reshape the array

x = np.arange(20).reshape(4,5)
print(x)
print(x.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)


In [38]:
# .ndim() - get the number of dimensions 

print(x.ndim)

2


### Practice Set 1 - Array Creation

1. Create a 1D array containing numbers from 1 to 10.
2. Create a 3x3 matrix of all zeros, and another of all ones.
3. Create an array of all even numbers between 2 and 20 (inclusive) using np.arange
4. Create 5 equally spaced values between 0 and 1 using np. linspace
5. Create a 4x4 identity matrix and print its shape, size, and ndim.
6. Create a 1D array of numbers 1-5 with dtype float - observe the output.

In [39]:
# Q1 

arr1 = np.arange(1, 11)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [40]:
# Q2

zeros = np.zeros((3, 3))
ones = np.ones((3, 3))
print(zeros)
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [41]:
# Q3

even = np.arange(2, 21, 2)
print(even)

[ 2  4  6  8 10 12 14 16 18 20]


In [42]:
# Q4

lin = np.linspace(0, 1, 5)
print(lin)

[0.   0.25 0.5  0.75 1.  ]


In [43]:
# Q5        

identity = np.eye(4)

print(identity)

print("Shape:", identity.shape)
print("Size:", identity.size)
print("Dimensions (ndim):", identity.ndim)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Shape: (4, 4)
Size: 16
Dimensions (ndim): 2


In [44]:
# Q6

arr = np.array([1, 2, 3, 4, 5], dtype=float)

print(arr)
print("Data Type:", arr.dtype)

[1. 2. 3. 4. 5.]
Data Type: float64


In [49]:
# 1D Indexing - Positive and Negative Indexing

arr=np.arange(10)
print(arr)
print(arr[-3:-12:-2])

[0 1 2 3 4 5 6 7 8 9]
[7 5 3 1]


In [ ]:
# 1D Slicing - [start:stop:step], reverse

In [46]:
# 2D Indexing - arr[row, col], full row, full column

arr = np.arange(20).reshape(5,4)
print(arr)
print(arr[2,2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
10


In [48]:
# 2D Slicing - Sub Matrix (block)

print(arr)
print(arr[1:4, 1:3])  # Slicing rows 1 to 3 and columns 1 to 2
print(arr[1,1:]) # Slicing row 1 and columns 1 to end

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 5  6]
 [ 9 10]
 [13 14]]
[5 6 7]


In [ ]:
# astype() - convert data type of array

x = np.array([1, 4, 4.3, 4.9, 4.8])
print(x)
print(x.astype('int32'))
print(x)

[1.  4.  4.3 4.9 4.8]
[1 4 4 4 4]
[1.  4.  4.3 4.9 4.8]


In [ ]:
# Boolean Indexing - arr[condition]