### NumPy Fundamentals

> Flow: array 

In [4]:
# arithmetic - array with scalar, array with array

import numpy as np

arr1 = np.arange(10)
print(arr1)
arr1=arr1 + 5
print("Multiply",arr1*5)
print("Exponent",arr1**2)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
Multiply [25 30 35 40 45 50 55 60 65 70]
Exponent [ 25  36  49  64  81 100 121 144 169 196]
[ 5  6  7  8  9 10 11 12 13 14]


In [5]:
# Sum Arithmetic operations on two arrays

x = np.arange(10)
y = np.arange(11,21)
print(x)
print(y)
print("Sum",x+y)

[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19 20]
Sum [11 13 15 17 19 21 23 25 27 29]


In [7]:
# comparison operators - boolean arrays

x = np.arange(5)
y = np.arange(1,6)
print(x==y)
print(x>y)
print(y>x)

[False False False False False]
[False False False False False]
[ True  True  True  True  True]


### np.random()

> Flow: seed (why reproductibility matters) -> rand -> randn -> randint (high excluded) -> choice -> shuffle

In [11]:
# np.random.seed() - set the random seed; np.random.rand() - generate random numbers

np.random.seed(2)
np.random.rand(5)
np.random.randn(10)

array([-1.07445552, -0.61722311, -1.50100687,  0.8935898 ,  0.73954567,
       -1.42356496, -1.11072776,  0.08858007, -1.35423054,  0.05827069])

In [12]:
# np.random.randint(low,high,size) - generate random integers

np.random.randint(10,20,size=(5,3))

array([[17, 16, 11],
       [13, 15, 18],
       [14, 16, 13],
       [19, 12, 10],
       [14, 12, 14]])

In [ ]:
# np.random.choice()

lst = [3,4,5,6,7,8,9]
np.random.choice(lst, 3, replace=False)
np.random.choice(10,5,replace=False)

array([5, 4, 3, 9, 2])

In [ ]:
# np.random.shuffle()

arr = np.arange(10)
np.random.shuffle(arr)
print(arr)

[1 6 5 4 2 7 8 0 3 9]


## Questions

1. Set seed = 42 and simulate 10 dice rolls (values 1-6) using randint

2. Generate 20 random marks between 35 and 100. Find the mean, max, min, and std.

3. Create a 3x4 random integer matrix (values 10-50). Find the column-wise mean and row-wise sum.

4. In the marks array from @2. find the index of the topper.

5. Using np. random. choice, randomly select 3 students from ['Aman', 'Priya', 'Rahul", 'Sneha', 'Vikram'].

In [17]:
# Q1

np.random.seed(42)

dice_rolls = np.random.randint(1, 7, 10)
print("Dice Rolls:")
print(dice_rolls)

Dice Rolls:
[4 5 3 5 5 2 3 3 3 5]


In [ ]:
# Q2



In [ ]:
# Q3

In [ ]:
# Q4

In [ ]:
# Q5

In [20]:
# min, max, sum, mean, meadian, std

arr = np.arange(6).reshape(2,3)
print(arr)
print("Min:",np.min(arr))
print("Row Min:",np.min(arr,axis=1))
print("Column Min:",np.min(arr,axis=0))

print("Sum of Arr:", arr.sum())
print("Sum of Rows:", arr.sum(axis=1))
print("Sum of Columns:", arr.sum(axis=0))

[[0 1 2]
 [3 4 5]]
Min: 0
Row Min: [0 3]
Column Min: [0 1 2]
Sum of Arr: 15
Sum of Rows: [ 3 12]
Sum of Columns: [3 5 7]
