# NumPy Broadcasting

The problem it solves:
- Normal arithmetic works position by position, so both arrays must have the same shape
- Real data almost never matches: 100 students x 3 subjects, but only 3 bonus values to add
- Looping over this would be slow and clumsy
- Broadcasting = when shapes differ, NumPy "stretches" the smaller array to fit the bigger one
- The stretching is virtual - no copies are made in memory, which is why it stays fast
- You have already used it: in arr + 5, the single number 5 is stretched across every element

In [4]:
import numpy as np

arr = np.arange(24).reshape(3,4,2)
# arr1 = np.arange(12).reshape()

### Nested np.where

- np.where handles two outcomes; for three or more, put another np.where in the "false" slot
- Meaning: "if the first test failed, here is the next test to try"
- Order is critical: check the highest threshold first
- If you tested >= 50 before >= 75, every strong student would be caught by 50 and nobody would get an A

In [ ]:
# np.where(condition, x, y) - returns elements chosen from x or y depending on condition.

import numpy as np
marks = np.array([92, 61, 45, 78, 33, 55])

grades = np.where(marks >= 75, 'A', # 'A' means marks >= 75 and 'B' means marks >= 50 and 'C' means marks < 50
         np.where(marks >= 50, 'B', 'C'))
print(marks)
print(grades)

[92 61 45 78 33 55]
['A' 'B' 'C' 'A' 'C' 'B']


## Linear Algebra Operations

### Element-wise multiplication vs the dot product

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a * b     :", a * b)          # element-wise
print("np.dot    :", np.dot(a, b))   # 1*4 + 2*5 + 3*6
print("a @ b     :", a @ b)          # same thing, modern syntax 

a * b     : [ 4 10 18]
np.dot    : 32
a @ b     : 32


### Transpose

In [ ]:
x = np.array([[1,2,3],[4,5,6]])
print(x)
print(x.T) 
print(x@x.T) 

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[14 32]
 [32 77]]


In [5]:
# reshape(rows, cols) - returns a new array with the same data but a new shape.

arr = np.arange(10)
print(arr.shape)
arr1=arr.reshape(1,-1)
arr2=arr.reshape(-1,1)
print("Row vector:", arr1)
print("Column vector:", arr2)

(10,)
Row vector: [[0 1 2 3 4 5 6 7 8 9]]
Column vector: [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [ ]:
# np.newaxis() - turn 1D into a row vector or column vector.

arr = np.arange(5)
print("Original array:", arr)
row_vector = arr[np.newaxis, :] # : means all elements in that dimension, np.newaxis adds a new dimension
column_vector = arr[:, np.newaxis]
print("Row vector:", row_vector)
print("Column vector:", column_vector)

Original array: [0 1 2 3 4]
Row vector: [[0 1 2 3 4]]
Column vector: [[0]
 [1]
 [2]
 [3]
 [4]]


In [ ]:
# flatten() vs ravel()
# flatten() -> returns a copy (own memory, original always safe, costs time/memory)
# ravel() -> returns a view (shared memory, original can be modified, fast)

m = np.array([[1, 2, 3],
              [4, 5, 6]])

f = m.flatten()
r = m.ravel()
print("flatten:", f)
print("ravel  :", r)

f[0] = 999          # modifying the copy and 999 means that the original matrix is not modified
r[1] = 888          # modifying the view and 888 means that we are modifying the original matrix as well by changing the view to 888
print("\noriginal matrix after both edits:")
print(m)

flatten: [1 2 3 4 5 6]
ravel  : [1 2 3 4 5 6]

original matrix after both edits:
[[  1 888   3]
 [  4   5   6]]


In [9]:
# vstack() - stack arrays in sequence vertically (row wise)
# hstack() - stack arrays in sequence horizontally (column wise)

A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8, 9]])

print("vstack:")
print(np.vstack((A, B)), "-> shape", np.vstack((A, B)).shape)

C = np.array([[10],
              [20]])
print("\nhstack:")
print(np.hstack((A, C)), "-> shape", np.hstack((A, C)).shape)

vstack:
[[1 2 3]
 [4 5 6]
 [7 8 9]] -> shape (3, 3)

hstack:
[[ 1  2  3 10]
 [ 4  5  6 20]] -> shape (2, 4)


In [10]:
# np.concatenate() - joins a sequence of arrays along an existing axis.

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("axis=0:\n", np.concatenate((A, B), axis=0))
print("\naxis=1:\n", np.concatenate((A, B), axis=1))

axis=0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

axis=1:
 [[1 2 5 6]
 [3 4 7 8]]
