# NumPy Broadcasting

The problem it solves:
- Normal arithmetic works position by position, so both arrays must have the same shape
- Real data almost never matches: 100 students x 3 subjects, but only 3 bonus values to add
- Looping over this would be slow and clumsy
- Broadcasting = when shapes differ, NumPy "stretches" the smaller array to fit the bigger one
- The stretching is virtual - no copies are made in memory, which is why it stays fast
- You have already used it: in arr + 5, the single number 5 is stretched across every element

In [ ]:
import numpy as np

arr = np.arange(24).reshape(3,4,2)
arr1 = np.arange(12).reshape()

### Nested np.where

- np.where handles two outcomes; for three or more, put another np.where in the "false" slot
- Meaning: "if the first test failed, here is the next test to try"
- Order is critical: check the highest threshold first
- If you tested >= 50 before >= 75, every strong student would be caught by 50 and nobody would get an A

In [2]:
import numpy as np
marks = np.array([92, 61, 45, 78, 33, 55])

grades = np.where(marks >= 75, 'A',
         np.where(marks >= 50, 'B', 'C'))
print(marks)
print(grades)

[92 61 45 78 33 55]
['A' 'B' 'C' 'A' 'C' 'B']


## Linear Algebra Operations

### Element-wise multiplication vs the dot product

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a * b     :", a * b)          # element-wise
print("np.dot    :", np.dot(a, b))   # 1*4 + 2*5 + 3*6
print("a @ b     :", a @ b)          # same thing, modern syntax 

a * b     : [ 4 10 18]
np.dot    : 32
a @ b     : 32


### Transpose

In [ ]:
x = np.array([[1,2,3],[4,5,6]])
print(x)
print(x.T) 
print(x@x.T) 

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[14 32]
 [32 77]]
